config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :questions, only: [:index]
  get '/users/import', to: 'users#import'
  post '/users/import', to: 'users#import_file'
  resources :users
  resources :courses do
    resources :questions, only: [:show, :new, :edit, :create, :update, :destroy, :upvote, :downvote] do
      member do
        post 'upvote'
        post 'downvote'
      end
      resources :answers do
        member do
          post 'upvote'
          post 'downvote'
        end
      end
    end
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :welcome, :path => '/'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :course
  has_many   :votes
  has_many :answers, dependent: :destroy
  
  #Validation
  validates :title, presence: true
  validates :description, presence: true
  
  def up_vote(user_id)
    @vote = get_user_vote(user_id)
    if @vote
      @vote.destroy()
    else
      @vote = votes.create(user_id: user_id)
  	  @vote.up
    end
  end
  
  def down_vote(user_id)
  	@vote = get_user_vote(user_id)
    if @vote
      @vote.destroy()
    else
      @vote = votes.create(user_id: user_id)
  	  @vote.down
    end
  end
  
  def get_user_vote(user_id)
    #loop through existing votes and make sure user has not previously voted
    votes.each do |v|
      if v.user_id == user_id
        @vote = v
      end
    end
    return @vote
  end

  def get_score
  	score = 0
  	votes.each do |v|
  		if v.status == 1
  			score = score + 1
  		else
  			score = score - 1
  		end
  	end
  	score
  end
  
  def self.search(title, keyword, course_id, user_id)
    @results = self.all
    if title && title != ""
      @results = @results.where("title LIKE :title", title: "%#{title}%")
    end
    if keyword && keyword != ""
      @results = @results.where("description LIKE :keyword", keyword: "%#{keyword}%")
    end
    if course_id && course_id != ""  && course_id =~ /^[0-9]+$/ && course_id.to_i() >-1 && Course.find(course_id.to_i())
      @results = @results.where("course_id = ?", course_id)
    end
    if user_id && user_id != "" && user_id =~ /^[0-9]+$/ && user_id.to_i() >-1 && User.find(user_id.to_i())
      @results = @results.where("user_id = ?", user_id)
    end
    return @results
  end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.search(params[:title],params[:keyword],params[:course],params[:poster])
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    if logged_in?
      @question = Question.new
    else
      redirect_to :back
    end
    
  end

  # GET /questions/1/edit
  def edit
    if logged_in? && (@question.user == current_user ||  current_user.is_admin?) 
    
    else
      redirect_to :back
    end
  end

  # POST /questions
  # POST /questions.json
  def create
    
    if logged_in?
      
      @course = Course.find(params[:course_id])
      @question = @course.questions.create(question_params)
    
      respond_to do |format|
        @question.user_id = current_user.id
        if @question.save
          @question.up_vote(current_user.id)
          format.html { redirect_to course_question_path(@question.course,@question), notice: 'Question was successfully created.' }
          format.json { render :show, status: :created, location: @question }
        else
          format.html { render :new }
          format.json { render json: @question.errors, status: :unprocessable_entity }
        end
      end
      
    else
      flash[:danger] = 'You must be logged in to post questions!' # Not quite right!
      redirect_to :back
    end
    
    
  end
  
  # POST /questions/X/upvote
  def upvote()
    @course = Course.find(params[:course_id])
    @question = @course.questions.find(params[:id])
    if logged_in?
      @question.up_vote(current_user.id)
    else
      flash[:danger] = 'You must be logged in to upvote questions!' # Not quite right!
    end
    redirect_to(course_question_path(@question.course,@question))
  end
  
  # POST /questions/X/downvote
  def downvote()
    @course = Course.find(params[:course_id])
    @question = @course.questions.find(params[:id])
    if logged_in?
      @question.down_vote(current_user.id)
    else
      flash[:danger] = 'You must be logged in to downvote questions!' # Not quite right!
    end
    redirect_to(course_question_path(@question.course,@question))
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    if logged_in? && (@question.user == current_user ||  current_user.is_admin?) 
      respond_to do |format|
        if @question.update(question_params)
          format.html { redirect_to course_question_path(@question.course,@question), notice: 'Question was successfully updated.' }
          format.json { render :show, status: :ok, location: @question }
        else
          format.html { render :edit }
          format.json { render json: @question.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :back
    end
    
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    if logged_in? && (@question.user == current_user ||  current_user.is_admin?) 
      @course = Course.find(params[:course_id])
      @question = @course.questions.find(params[:id])
      @question.destroy
      respond_to do |format|
        format.html { redirect_to course_path(@course), notice: 'Question was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to :back
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Course.find(params[:course_id]).questions.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :description, :user_id, :course_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for([question.course,question]) do |f|  %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
   </div>
 
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
   </div>

   <% if !logged_in? %>
      <%= "you need to be logged in to post" %>
  <% elsif %>
      <%= "posting as  #{current_user.name} (#{current_user.email})" %><br>
  <% end %>

  <br>
  <button class="mdl-button mdl-button--raised mdl-button--colored mdl-js-button mdl-js-ripple-effect" type="submit" >Ask Question</button>
  
<% end %>

app/views/questions/_question.html.erb
<div class="question">
    <h3><%= link_to question.title, course_question_path(question.course,question) %></h3> 
    <hr style="margin: .5em 0;">
    <%= question.description %>
    
    <p class="author">
        asked by <%= link_to question.user.name, url_for(question.user) %>
    </p>
</div>
<br>

app/views/questions/_vote.html.erb
Votes: <%= @question.get_score() %>
      <% if current_user && current_user.upvoted_question?(@question) %>
      <%=link_to image_tag(image_url("upvote_done.png"), :size => "20x20"), upvote_course_question_path(@question.course, @question), remote: true , method: :post  %>
    <% else %>
      <%=link_to image_tag(image_url("upvote.png"), :size => "20x20"), upvote_course_question_path(@question.course, @question), remote: true , method: :post  %>
    <% end %>
    <% if current_user && current_user.downvoted_question?(@question) %>
      <%=link_to image_tag(image_url("downvote_done.png"), :size => "20x20"), downvote_course_question_path(@question.course, @question), remote: true , method: :post  %>
    <% else %>
      <%=link_to image_tag(image_url("downvote.png"), :size => "20x20"), downvote_course_question_path(@question.course, @question), remote: true , method: :post  %>
    <% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', course_question_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="question-page">
  <h1>Search:</h1>
  <%= form_tag questions_path, :method => 'get' do %>
    <p>
      <strong>Title:</strong><br>
      <%= text_field_tag :title, params[:title] %>
      <br>
      <strong>Keyword:</strong><br>
      <%= text_field_tag :keyword, params[:keyword] %>
      <br>
      <strong>In Course:</strong><br>
      <%= select_tag :course, options_from_collection_for_select(Course.all, "id", "full_name",params[:course]), prompt: "Select Course" %>
      <br>
      <strong>By User:</strong><br>
      <%= select_tag :poster, options_from_collection_for_select(User.all, "id", "name",params[:poster]), prompt: "Select User"  %>
      <br>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>
</div>

<% if @questions %>
<div class="question-page">
  <h1>Results:</h1>
  <% if @questions.count > 0 %>
    <% @questions.each do |question| %>
      <div class="question">
        <h1>
          <strong><%= link_to question.title , course_question_path(question.course.id, question.id) %></strong> 
        </h1>
        <p class="subheader">
          by <% if question.user %><%= link_to question.user.name, url_for(question.user) %><% end %> 
          <% if current_user && (current_user.is_admin? || current_user.id == question.user_id) %>
          (<%= link_to 'Edit Question', edit_course_question_path(question.course,question) %> | <%= link_to 'Delete Question', [question.course, question], method: :delete, data: { confirm: 'Are you sure?' } %>)
          <% end %>
           -- Posted in <% if question.course %><%= link_to (question.course.name + " " + question.course.code), url_for(question.course) %><% end %>
        </p>
        
        <% if current_user && current_user.upvoted_question?(question) %>
          <%=link_to image_tag(image_url("upvote_done.png"), :size => "15x15"), upvote_course_question_path(question.course, question), method: :post  %>
        <% else %>
          <%=link_to image_tag(image_url("upvote.png"), :size => "15x15"), upvote_course_question_path(question.course, question), method: :post  %>
        <% end %>
        Votes: <%= question.get_score() %>
        <br>
            <% if current_user && current_user.downvoted_question?(question) %>
          <%=link_to image_tag(image_url("downvote_done.png"), :size => "15x15"), downvote_course_question_path(question.course, question), method: :post  %>
        <% else %>
          <%=link_to image_tag(image_url("downvote.png"), :size => "15x15"), downvote_course_question_path(question.course, question), method: :post  %>
        <% end %>
        
        <br>
        <br>
        <%= question.description %>
        <br>
        <br>
      </div> 
    <% end %>
  <% else %>
    <strong>No questions found that match your query!</strong> 
  <% end %>
  
  </div>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<div class="question-page">
  
  <div class="description">
    <p id="notice"><%= notice %></p>
    <h1>
      <strong><%= @question.title %></strong> 
    </h1>
    <% flash.each do |message_type, message| %>
  		<div class="alert alert-<%= message_type %>"><%= message %></div>
	  <% end %>
    <p class="subheader">
      by <% if @question.user %><%= link_to @question.user.name, url_for(@question.user) %><% end %> 
      <br>
      <% if current_user && (current_user.acct_type==0 || current_user.id == @question.user_id) %>
      (<%= link_to 'Edit Question', edit_course_question_path(@question.course,@question) %> | <%= link_to 'Delete Question', [@question.course, @question], method: :delete, data: { confirm: 'Are you sure?' } %>)
      <% end %>    
    </p>
    
    <div id="vote_count">
      Votes: <%= @question.get_score() %>
      <% if current_user && current_user.upvoted_question?(@question) %>
      <%=link_to image_tag(image_url("upvote_done.png"), :size => "20x20"), upvote_course_question_path(@question.course, @question), remote: true , method: :post  %>
    <% else %>
      <%=link_to image_tag(image_url("upvote.png"), :size => "20x20"), upvote_course_question_path(@question.course, @question), remote: true , method: :post  %>
    <% end %>
    <% if current_user && current_user.downvoted_question?(@question) %>
      <%=link_to image_tag(image_url("downvote_done.png"), :size => "20x20"), downvote_course_question_path(@question.course, @question), remote: true , method: :post  %>
    <% else %>
      <%=link_to image_tag(image_url("downvote.png"), :size => "20x20"), downvote_course_question_path(@question.course, @question), remote: true , method: :post  %>
    <% end %>
    </div>
    
    <br>
    <br>
    <%= @question.description %>
    <br>
    <br>
    <p>
    -- Posted in <% if @question.course %><%= link_to (@question.course.name + " " + @question.course.code), url_for(@question.course) %><% end %>
    </p>
    <%= link_to 'Back', :back, :class => "mdl-button mdl-button--colored mdl-js-button mdl-button--raised mdl-js-ripple-effect" %>
    
  </div>
  <br>
  <div class="answers">
    <h2>Answers:</h2>
    <%= render @question.answers %>


    <strong>Add an answer:</strong>
    <%= render "answers/form", question:@question, answer:@question.answers.build  %>
  </div>
  <div style="clear: both"></div> <!-- This goes after the last floated element - no floating elements are allowed on either side of this. -->
  
</div>

app/views/questions/show.js.erb
$("#vote_count").html("<%= j render(partial: 'vote') %>");