config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :questions, only: [:index]
  get '/users/import', to: 'users#import'
  post '/users/import', to: 'users#import_file'
  resources :users
  resources :courses do
    resources :questions, only: [:show, :new, :edit, :create, :update, :destroy, :upvote, :downvote] do
      member do
        post 'upvote'
        post 'downvote'
      end
      resources :answers do
        member do
          post 'upvote'
          post 'downvote'
        end
      end
    end
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :welcome, :path => '/'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  has_many   :votes, dependent: :destroy

  def up_vote(user_id)
    @vote = get_user_vote(user_id)
    if @vote
      @vote.destroy()
    else
      @vote = votes.create(user_id: user_id)
  	  @vote.up
    end
  end
  
  def down_vote (user_id)
    @vote = get_user_vote(user_id)
    if @vote
      @vote.destroy()
    else
      @vote = votes.create(user_id: user_id)
      @vote.down
    end
  end
  
  def get_user_vote(user_id)
    #loop through existing votes and make sure user has not previously voted
    votes.each do |v|
      if v.user_id == user_id
        @vote = v
      end
    end
    return @vote
  end

  def get_score
  	score = 0
  	votes.each do |v|
  		if v.status == 1
  			score = score + 1
  		else
  			score = score - 1
  		end
  	end
  	score
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    if logged_in?
      @answer = Answer.new
    else
      redirect_to :back
    end
    
  end

  # GET /answers/1/edit
  def edit
    if logged_in? && (@answer.user == current_user ||  current_user.is_admin?) 
    
    else
      redirect_to :back
    end
  end

  # POST /answers
  # POST /answers.json
  def create
    
    @course = Course.find(params[:course_id])
    @question = @course.questions.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
    
    if !logged_in?
      flash[:danger] = 'You must be logged in to post questions!' # Not quite right!
      redirect_to course_question_path(@course,@question)
    else
      respond_to do |format|
        @answer.user_id = current_user.id
        if @answer.save
          @answer.up_vote(current_user.id)
          format.html { redirect_to course_question_path(@course,@question), notice: 'Answer was successfully created.' }
          format.json { render :show, status: :created, location: @answer }
        else
          format.html { render :new }
          format.json { render json: @answer.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    if logged_in? && (@answer.user == current_user ||  current_user.is_admin?) 
      respond_to do |format|
        if @answer.update(answer_params)
          format.html { redirect_to course_question_path(@answer.question.course,@answer.question), notice: 'Answer was successfully updated.' }
          format.json { render :show, status: :ok, location: @answer }
        else
          format.html { render :edit }
          format.json { render json: @answer.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :back
    end
    
  end
  
  # POST /questions/X/answers/Y/upvote
  def upvote()
    @course = Course.find(params[:course_id])
    @question = @course.questions.find(params[:question_id])
    if logged_in?
      @answer = @question.answers.find(params[:id])
      @answer.up_vote(current_user.id)
    else
      flash[:danger] = 'You must be logged in to upvote answers!' # Not quite right!
    end
    redirect_to(course_question_path(@question.course,@question))
  end
  
  # POST /questions/X/answers/Y/downvote
  def downvote()
    @course = Course.find(params[:course_id])
    @question = @course.questions.find(params[:question_id])
    if logged_in?
      @answer = @question.answers.find(params[:id])
      @answer.down_vote(current_user.id)
    else
      flash[:danger] = 'You must be logged in to downvote answers!' # Not quite right!
    end
    redirect_to(course_question_path(@question.course,@question))
  end


  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    if logged_in? && (@answer.user == current_user ||  current_user.is_admin?) 
      @answer.destroy
      respond_to do |format|
       format.html { redirect_to course_question_path(@answer.question.course,@answer.question), notice: 'Answer was successfully destroyed.' }
       format.json { head :no_content }
      end
    else
      redirect_to :back
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Course.find(params[:course_id]).questions.find(params[:question_id]).answers.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:description, :question_id, :user_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class="answer" id="answer">
    <%= answer.description %><br>
    Votes: <%= answer.get_score() %>
    <% if current_user && current_user.upvoted_answer?(answer) %>
      <%=link_to image_tag(image_url("upvote_done.png"), :size => "20x20"), upvote_course_question_answer_path(answer.question.course,answer.question,answer), method: :post  %>
    <% else %>
      <%=link_to image_tag(image_url("upvote.png"), :size => "20x20"), upvote_course_question_answer_path(answer.question.course,answer.question,answer), method: :post  %>
    <% end %>
    <% if current_user && current_user.downvoted_answer?(answer) %>
      <%=link_to image_tag(image_url("downvote_done.png"), :size => "20x20"), downvote_course_question_answer_path(answer.question.course,answer.question,answer), method: :post  %>
    <% else %>
      <%=link_to image_tag(image_url("downvote.png"), :size => "20x20"), downvote_course_question_answer_path(answer.question.course,answer.question,answer), method: :post  %>
    <% end %>
    <p class="author">
        by <%= link_to answer.user.name, url_for(answer.user) %> 
        <% if current_user && (current_user.is_admin? || current_user.id == answer.user_id) %>
        (<%= link_to 'Edit Answer', edit_course_question_answer_path(answer.question.course,answer.question,answer) %> | <%= link_to 'Delete Answer', [answer.question.course,answer.question, answer], method: :delete, data: { confirm: 'Are you sure?' } %>)
        <% end %>
    </p>
</div>
<br>

app/views/answers/_form.html.erb
<%= form_for([answer.question.course,answer.question,answer]) do |f|  %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <% if !logged_in? %>
    <%= "you must be logged in to answer a question." %>
  <% else %>
    <%= "answering as #{current_user.name} (#{current_user.email})" %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', course_question_path(@answer.question.course,@answer.question) %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Question</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.description %></td>
        <td><%= answer.question %></td>
        <td><%= answer.user %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @answer.description %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', :back, :class => "mdl-button mdl-button--colored mdl-js-button mdl-button--raised mdl-js-ripple-effect" %>