config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :questions, only: [:index]
  get '/users/import', to: 'users#import'
  post '/users/import', to: 'users#import_file'
  resources :users
  resources :courses do
    resources :questions, only: [:show, :new, :edit, :create, :update, :destroy, :upvote, :downvote] do
      member do
        post 'upvote'
        post 'downvote'
      end
      resources :answers do
        member do
          post 'upvote'
          post 'downvote'
        end
      end
    end
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :welcome, :path => '/'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    if logged_in? && (current_user.is_admin?) 
      @course = Course.new
    else
      redirect_to :back
    end
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    
    if logged_in? && (current_user.is_admin?) 
      @course = Course.new(course_params)

      respond_to do |format|
        if @course.save
          format.html { redirect_to @course, notice: 'Course was successfully created.' }
          format.json { render :show, status: :created, location: @course }
        else
          format.html { render :new }
          format.json { render json: @course.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :back
    end
    
    
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    
    if logged_in? && (current_user.is_admin?) 
      respond_to do |format|
        if @course.update(course_params)
          format.html { redirect_to @course, notice: 'Course was successfully updated.' }
          format.json { render :show, status: :ok, location: @course }
        else
          format.html { render :edit }
          format.json { render json: @course.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :back
    end
    
    
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    if logged_in? && (current_user.is_admin?) 
      @course.destroy
      respond_to do |format|
        format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to :back
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :code, :desc, :image_url)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div class="user_course">
    <h3><%= link_to "#{course.name} #{course.code}", course_path(course) %></h3> 
    
</div>
<br>

app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  
  <div class="field">
    <%= f.label :desc %>
    <%= f.text_field :desc %>
  </div>
  
  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h3 style="color: grey;">Courses</h3><hr> 

  
<main class="mdl-layout__content">
  <div class="page-content">
    <div class="mdl-grid ">
      <% @courses.each do |course| %>

        <div class="demo-card-square mdl-card mdl-shadow--2dp mdl-cell mdl-cell--2-col mdl-layout-spacer mdl-shadow--8dp" style="width: 320px; height: 320px;">
          <div class="mdl-card__title mdl-card--expand" style="background:url('<%= course.image_url %>') bottom right 15% no-repeat #9E9E9E; background-size: 100% 100%;">
            <h2 class="mdl-card__title-text"><%= course.name %> <%= course.code %></h2>
          </div>
          <div class="mdl-card__supporting-text">
            <%= course.desc %>
          </div>
          <div class="mdl-card__actions mdl-card--border">
            <a class="mdl-button mdl-button--raised mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="<%= url_for(course) %>">
              View Course
            </a>
            <div class="material-icons mdl-badge mdl-badge--overlap mdl-color-text--blue-grey-300" data-badge="<%= course.questions.count %>" style="margin-left: 200px;">comment</div>
          </div>
        </div>
    <% end %>
    </div>
  </div>
</main>

<br>
<% if current_user && current_user.is_admin? %>
<a button class="mdl-button mdl-button--colored mdl-js-button mdl-button--raised mdl-js-ripple-effect" href="<%= new_course_path %>">Add Course</button></a>
<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<div class="course">
  
  <div class="description">
    <img src='<%= @course.image_url %>' alt="Mountain View" class="classimg">
    <p id="notice"><%= notice %></p>
    <h1>
      <strong><%= @course.name %> <%= @course.code %></strong>
    </h1>
    	<% flash.each do |message_type, message| %>
  		<div class="alert alert-<%= message_type %>"><%= message %></div>
	<% end %>
	
	  <% if current_user && current_user.is_admin? %>
    <p class="subheader">
       <a button class="mdl-button mdl-button--colored mdl-js-button mdl-button--raised mdl-js-ripple-effect" href="<%=@course.id%>/edit"></button>Edit Course</a>
       <a button class="mdl-button mdl-button--colored mdl-js-button mdl-button--raised mdl-js-ripple-effect" <%= link_to 'Delete Course', @course, method: :delete, data: { confirm: 'Are you sure?' } %> </button></a>
    </p>
    <% end %>
    <hr>
    <%= @course.desc %>
    <br>
    <br>
    Being taught by: <%= format_users(@course.get_teachers).html_safe %>
    <br>
    <br>
    Enrolled students: <%= format_users(@course.get_students).html_safe %>
    <br>
    <br>
    <br>
    <%= link_to 'Back', :back, :class => "mdl-button mdl-button--colored mdl-js-button mdl-button--raised mdl-js-ripple-effect" %>
  </div>
  <br>
  <div class="questions">
    <h2>Questions:</h2>
    <%= render @course.questions %>


    <strong>Add a question:</strong>
    <%= render "questions/form", course:@course, question:@course.questions.build  %><br>
  </div>
  <div style="clear: both"></div> <!-- This goes after the last floated element - no floating elements are allowed on either side of this. -->
  
</div>